
DIRECCION_ARRIBA = 0
DIRECCION_ABAJO = 1
DIRECCION_IZQUIERDA = 2
DIRECCION_DERECHA = 3
UPDATES_PER_FRAME = 5
CHARACTER_SCALING = 0.5
MOVEMENT_SPEED = 20 * CHARACTER_SCALING
DEAD_ZONE = 0.17
SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1240
